### ISSUE TITLE
Sections not working

### ISSUE THREAD

**Issue by 0zguner** [dangthaison91/RxTextureDataSources#1]
I believe its Texture issue. Is there any work around ?

**Comment by dangthaison91** [comment]
Can you provide more detail @mzgnr ?

**Comment by 0zguner** [comment]
@dangthaison91 I've just tried your example project and sections didnt work

**Comment by 0zguner** [comment]
Its the screenshot 

![screen shot 2017-08-16 at 05 48 02](https://user-images.githubusercontent.com/6003317/29345299-8cb4625a-8246-11e7-9236-93aeac345cc3.png)

**Comment by dangthaison91** [comment]
@mzgnr Sorry, I was so busy with company project today. Can you share info or your solution if have?

**Comment by 0zguner** [comment]
@dangthaison91 I'll send a PR later 😄

**Comment by 0zguner** [comment]
@dangthaison91 i think i'm about to lose my mind dude. I cloned your project. I'll share it with texture guys

**Comment by 0zguner** [comment]
@dangthaison91 you can take a look at https://github.com/mzgnr/RxTextureDataSources
