### ISSUE TITLE
Can't use RxASTableAnimatedDataSource class

### ISSUE THREAD

**Issue by vienvn** [dangthaison91/RxTextureDataSources#12]
I think we must change RxASTableAnimatedDataSource to publish.

**Comment by dangthaison91** [comment]
Think I've made a mistake by change the access level from **open** to **final**. I will better to be **open**. Please check the version 0.3.2 again and thanks for reporting @vienvn

**Comment by vienvn** [comment]
It works OK. Thanks

**Comment by johnldeguzman** [comment]
Any way to merge 0.3.2 to master?

**Comment by dangthaison91** [comment]
@johnldeguzman Waiting 2nd contributor to help to review the PR #13  so we can merge it into master.
