### ISSUE TITLE
Delegate methods not being called

### ISSUE THREAD

**Issue by foxware00** [dangthaison91/RxTextureDataSources#21]
I'm unable to get delegate methods to be called. I can't obviously set `tableNode.dataSource = self` and it seems all of the delegate methods fail to be called

I can't find an alternative for the following from RxDataSources

```
tableView.rx.setDelegate(self)
     .disposed(by: disposeBag)
```

however I am setting `tableNode.delegate = self` and still nothing
None of the following ever get triggered 

`func tableNode(_ tableNode: ASTableNode, willBeginBatchFetchWith context: ASBatchContext) {`

`func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath) -> [UITableViewRowAction]? {`

`func shouldBatchFetch(for tableNode: ASTableNode) -> Bool {`
... etc

**Comment by dangthaison91** [comment]
@foxware00 Thanks for report issue, I will check it on weekend.

**Comment by foxware00** [comment]
@dangthaison91 Great thanks, let me know if there is any more information I can provide

**Comment by foxware00** [comment]
@dangthaison91 Turns out this was because my ASTableDataSource,  ASTableDelegate protocols were extending a generic base class. As soon as I moved them into the concrete class they seems to be fired. Seems like an issue with swift. Can close for now

**Comment by fumito-ito** [comment]
@foxware00 thanks  for your reporting ! I close it.
