### ISSUE TITLE
How to made datasource keep the old array of data if the new one is no different from the old one?

### ISSUE THREAD

**Issue by vldalx** [dangthaison91/RxTextureDataSources#25]
I'm developing an iOS app adhering to MVVM pattern and using RxASDataSources.

The application algorithm:
1. The app fetches an array of data from my BE. 
2. Each element of the array is mapped to a `viewmodel` instance.
3. The array is passed to RxASDataSources.
4. Inside `configureCell` closure each viewmodel is bound to a node. For example, `button.addTarget(viewmodel, action: #selector(didButtonTap), forControlEvents: .touchUpInside)`

The issue with the datasource is if the new array of data is no different from the previous one (e.g a user refreshed the list), the datasource replaces the old array with the new one internally, but doesn't notify the nodes. If a node keeps reference to an element from data source after such refresh the node keeps the old element, but the datasource contains a new one.

**Comment by fumito-ito** [comment]
@vldalx I cannot understand what is your problem. Can you upload sample problem to reproduce your problem or describe me more details ?

**Comment by vldalx** [comment]
@fumito-ito The code below shows the problem.

Initially, the first array of 10 items is passed to the datasource.
Then, in 5 seconds, the second array of 5 new items (the items are equal to the first items from the first array) is passed to the datasource.
Each ButtonCellNode holds an item from the first array, but the datasource contains the second array as a result of two previous steps.

You can run the code and you'll see the different output in console if you press any button immediately  after the app has been started and press the same button in 5 seconds.

``` Swift
typealias Section = AnimatableSectionModel<Int, ViewModel>

extension Int: IdentifiableType {
    public var identity: Int {
        return self
    }
}

final class ViewModel: IdentifiableType, Equatable, CustomDebugStringConvertible {
    private(set) var identity: Int
    private let debugText: String
    
    var debugDescription: String {
        return "\(debugText) - \(identity)"
    }
    
    init(id: Int, debugText text: String) {
        identity = id
        debugText = text
    }
    
    @objc func didButtonTap() {
        print("bound to node item: \(debugDescription)")
    }
    
    static func == (lhs: ViewModel, rhs: ViewModel) -> Bool {
        return lhs.identity == rhs.identity
    }
}

class ViewController: UIViewController {
    private let tableNode = ASTableNode()
    
    private lazy var dataSource: RxASTableAnimatedDataSource<Section> = { [unowned self] in
        RxASTableAnimatedDataSource<Section>(configureCell: { _, _, _, viewModel in
            let node = ButtonCellNode(viewModel: viewModel)

            node.buttonNode.addTarget(viewModel, action: #selector(ViewModel.didButtonTap), forControlEvents: .touchUpInside)
            node.buttonNode.addTarget(self, action: #selector(ViewController.didNodeButtonTap(_:)), forControlEvents: .touchUpInside)

            return node
        })
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.addSubnode(tableNode)
        
        let initialItems = (0...10).map { ViewModel(id: $0, debugText: "initial item") }
        let delayedItems = (0...5).map { ViewModel(id: $0, debugText: "delayed item") }
        
        let initialObservable = Observable.just(initialItems)
        let delayedObservable = Observable.just(delayedItems).delay(5, scheduler: MainScheduler.asyncInstance)
        
        Observable
            .merge([initialObservable, delayedObservable])
            .map { [Section(model: 0, items: $0)] }
            .bind(to: tableNode.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        tableNode.frame = view.bounds
    }
    
    @objc func didNodeButtonTap(_ buttonNode: ASButtonNode) {
        let buttonCellNode = buttonNode.supernode as! ButtonCellNode
        let index = buttonCellNode.viewModel.identity
        let viewModel = self.dataSource[IndexPath(row: index, section: 0)]
        
        print("item in datasource: \(viewModel.debugDescription)")
    }
}

final class ButtonCellNode: ASCellNode {
    let viewModel: ViewModel
    
    private(set) lazy var buttonNode: ASButtonNode = { [unowned self] in
        let buttonNode = ASButtonNode()
        buttonNode.setTitle(self.viewModel.debugDescription, with: nil, with: .darkGray, for: .normal)
        buttonNode.setTitle(self.viewModel.debugDescription, with: nil, with: .red, for: .highlighted)
        return buttonNode
    }()
    
    init(viewModel: ViewModel) {
        self.viewModel = viewModel
        super.init()
        selectionStyle = .none
        addSubnode(buttonNode)
    }
    
    override func layoutSpecThatFits(_ constrainedSize: ASSizeRange) -> ASLayoutSpec {
        buttonNode.style.preferredSize = CGSize(width: constrainedSize.max.height, height: 44)
        
        return ASCenterLayoutSpec(
            horizontalPosition: .center,
            verticalPosition: .center,
            sizingOption: .minimumSize,
            child: buttonNode)
    }
}
```

**Comment by fumito-ito** [comment]
Thanks @vldalx ! It looks a problem of RxDataSources. Do you reproduce this problem only under Rx"AS"DataSources ?

**Comment by fumito-ito** [comment]
@vldalx In my opinion, the problems are caused from confusing of `ItemType`'s property.
Under Differentiator context, `ItemType`'s `identity` and `==` have different meanings as following.

- `identity` shows identity of item. if item is same, this property should return `true`
- `==` shows equality of item. if item is changed (e.g. updated property), this property should return `false`

In your code, second viewModels have same id's but have different `debutText`. ViewModels have to notify changes of property through `==` to Differentiator.

For example, can you update `==` as following ?

```swift
static func == (lhs: ViewModel, rhs: ViewModel) -> Bool {
    return lhs.identity == rhs.identity && lhs.debugText == rhs.debugText
}
```

**Comment by vldalx** [comment]
@fumito-ito In my example `debugText` is only for debug to output in console. Of course, if  `==` operator returns `false` the node for such item will be reconfigured. But the case is two objects have the same `identity` and `==` returns `true`.

Let's say, my app has a newsfeed. The user is able to refresh it.
If the user has refreshed the newsfeed and any post hasn't been changed, the node for that post will still contain the old post object, but the data-source will contain the new one.

**Comment by vldalx** [comment]
By the way, if the initial array and the second array are equal the problem is gone.

Replace in the example 
``` Swift
let initialItems = (0...10).map { ViewModel(id: $0, debugText: "initial item") }
let delayedItems = (0...5).map { ViewModel(id: $0, debugText: "delayed item") }
```
with
``` Swift
let initialItems = (0...10).map { ViewModel(id: $0, debugText: "initial item") }
let delayedItems = (0...10).map { ViewModel(id: $0, debugText: "delayed item") }
```

**Comment by vldalx** [comment]
I've created RxSwiftCommunity/RxDataSources#250 issue in `RxDataSources` repo.
