### ISSUE TITLE
configureCell is called on a background queue (version 0.3.3)

### ISSUE THREAD

**Issue by vldalx** [dangthaison91/RxTextureDataSources#26]
After updating the version `configureCell` closure is called on a background queue. According to [the doc](http://texturegroup.org/appledoc/Protocols/ASTableDataSource.html#//api/name/tableNode:nodeForRowAtIndexPath:) it should be called on the main thread.

`configureCellBlock` has been added in #23. According to [the doc](http://texturegroup.org/appledoc/Protocols/ASTableDataSource.html#//api/name/tableNode:nodeBlockForRowAtIndexPath:) it can be called on the main thread or a background queue.

**Comment by fumito-ito** [comment]
It will be resolved by #14
