### ISSUE TITLE
Move RxASDataSources to RxSwiftCommunity?

### ISSUE THREAD

**Issue by gtsiap** [dangthaison91/RxTextureDataSources#3]
Hello, 

I found out about RxASDataSources a few days ago. 
I have also implemented a simpler  version of it internally in my company, 
because I didn’t know that someone else had developed one. 

This is duplicated efford. 

What do you think about moving this project to the RxSwiftCommunity?

Moving the project would make it easier for other developers to discover it and IMO it will offer
a better place for the community to contribute to it.

**Comment by dangthaison91** [comment]
Thanks for your suggestion @terietor ,
First, I need to resolve the issue with Travis-CI and confirm that update rows/cell-node functions work like RxDataSources.

Seem that cell nodes are not updated as expected.
