### ISSUE TITLE
RxSwift 5.+ Support

### ISSUE THREAD

**Issue by foxware00** [dangthaison91/RxTextureDataSources#32]
Currently, the builds support RxSwift 4.+ which is incompatible when using RxSwift 5.0.+ in the project. Making this unavailable to use with Swift 5 projects. Happy to open a PR, but will need some guidance getting the project working locally.

**Comment by dangthaison91** [comment]
@foxware00 You can simply run Carthage to update dependencies then you can start on Swift 5.0 migration.

**Comment by foxware00** [comment]
@dangthaison91 opened a PR #33. I've never used Carthage before so wasn't 100% sure what to upload. Just updated dependencies and did some very minor changes to support swift 5

**Comment by foxware00** [comment]
@dangthaison91 Do we need to do anything special to get the latest library version in cocoapods?

**Comment by dangthaison91** [comment]
@foxware00 Texture just stopped support iOS 8.0 in 2.8.1. I just set podspec to iOS 9.0 and trunk pod version to  0.4.
